package com.gslab.student.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Student")
public class Student {

	@DynamoDBHashKey(attributeName = "studentId")
	@DynamoDBAutoGeneratedKey
	private String studentId; 
	
	@DynamoDBAttribute(attributeName = "firstName")
	private String firstName;
	
	@DynamoDBAttribute(attributeName = "lastName")
	private String lastName;
	
	@DynamoDBAttribute(attributeName = "phoneNumber")
	private String phoneNumber;
	
	@DynamoDBAttribute(attributeName = "emailId")
	private String emailId;
	
	@DynamoDBAttribute(attributeName = "password")
	private String password;

	public String getStudentId() {
		return studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
}
