package com.gslab.exam.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;

@DynamoDBTable(tableName = "Question")
public class Question {
	
	@DynamoDBHashKey(attributeName = "queId")
	@DynamoDBAutoGeneratedKey
	private String queId;
	
	@DynamoDBAttribute(attributeName = "questionDesc")
	private String questionDesc;
	
	@DynamoDBAttribute(attributeName = "option1")
	private String option1;
	
	@DynamoDBAttribute(attributeName = "option2")
	private String option2;
	
	@DynamoDBAttribute(attributeName = "option3")
	private String option3;
	
	@DynamoDBAttribute(attributeName = "option4")
	private String option4;
	
	@DynamoDBAttribute(attributeName = "answer")
	private int answer;
	
	public Question() {
		
	}
	public String getQueId() {
		return queId;
	}
	public void setQueId(String queId) {
		this.queId = queId;
	}
	public String getQuestionDesc() {
		return questionDesc;
	}
	public void setQuestionDesc(String questionDesc) {
		this.questionDesc = questionDesc;
	}
	public String getOption1() {
		return option1;
	}
	public void setOption1(String option1) {
		this.option1 = option1;
	}
	public String getOption2() {
		return option2;
	}
	public void setOption2(String option2) {
		this.option2 = option2;
	}
	public String getOption3() {
		return option3;
	}
	public void setOption3(String option3) {
		this.option3 = option3;
	}
	public String getOption4() {
		return option4;
	}
	public void setOption4(String option4) {
		this.option4 = option4;
	}
	public int getAnswer() {
		return answer;
	}
	public void setAnswer(int answer) {
		this.answer = answer;
	}
	
	

}
